### ISSUE TITLE
Where is the project directory created?

### ISSUE THREAD

**Issue by scottkleinman** [whatevery1says/we1s-virtual-workspace#10]
I can't seem to find this, but I'm presuming that a project manifest should be created at the same time.

**Comment by jeremydouglass** [comment]
Briefly, it is created directly under the `new_topic_browser_project.ipynb` notebook -- that is in `notebooks`  in this repo.

1. open `new_topic_browser_project.ipynb`
2. configure `project_name` -- e.g. "manifest_test"
3. the new project, e.g. "manifest_test" will be included in the top-level "projects" folder (does not exist yet in repo) with a folder name that includes a datestamp: /notebooks/projects/YYYY_MM_DD_HHMM_manifest_test/
4. At the bottom of the `new_topic_browser_project.ipynb` notebook (after it runs) it generates a live link to the new project folder.

For more, see the README: 

-  https://github.com/whatevery1says/we1s-virtual-workspace/blob/master/notebooks/README.md
